/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 23:12:22 EET 2016
 */

package TileMap;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Background_ESTest extends Background_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Background background0 = new Background("vBM!uF{1QCQ", (-654.583304));
      background0.setVector((-3798.2397882258565), (-654.583304));
      background0.update();
  }

  @Test
  public void test1()  throws Throwable  {
      Background background0 = new Background("", (-800.309));
      background0.setVector(0.0, (-800.309));
  }

  @Test
  public void test2()  throws Throwable  {
      Background background0 = new Background("+)'zl%($CTo(uxPM1", 0.0);
      background0.setPosition(0.0, 930.798);
  }

  @Test
  public void test3()  throws Throwable  {
      Background background0 = new Background("\"_7mo", (-37.84092659591799));
      // Undeclared exception!
      try { 
        background0.draw((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.Background", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Background background0 = new Background("", (-441.563022137));
      background0.setPosition((-441.563022137), (-441.563022137));
  }
}
