/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 22:30:01 EET 2016
 */

package Entity.Enemies;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import TileMap.TileMap;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Slugger_ESTest extends Slugger_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      TileMap tileMap0 = new TileMap(4095);
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setVector((-1.0), 4095);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      TileMap tileMap0 = new TileMap(3426);
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setVector(3426, 0.0);
      slugger0.setLeft(true);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Slugger slugger0 = null;
      try {
        slugger0 = new Slugger((TileMap) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Entity.MapObject", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TileMap tileMap0 = new TileMap(280);
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setVector(280, 280);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      TileMap tileMap0 = new TileMap((-828));
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setRight(false);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test5()  throws Throwable  {
      TileMap tileMap0 = new TileMap(4095);
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setVector((-1.0), 4095);
      slugger0.setLeft(true);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test6()  throws Throwable  {
      TileMap tileMap0 = new TileMap(3426);
      Slugger slugger0 = new Slugger(tileMap0);
      slugger0.setLeft(true);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test7()  throws Throwable  {
      TileMap tileMap0 = new TileMap(4095);
      Slugger slugger0 = new Slugger(tileMap0);
      // Undeclared exception!
      try { 
        slugger0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.TileMap", e);
      }
  }

  @Test
  public void test8()  throws Throwable  {
      TileMap tileMap0 = new TileMap(9);
      Slugger slugger0 = new Slugger(tileMap0);
      // Undeclared exception!
      try { 
        slugger0.draw((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Entity.MapObject", e);
      }
  }
}
