/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 23:25:17 EET 2016
 */

package Entity;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Explosion_ESTest extends Explosion_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Explosion explosion0 = new Explosion((-4423), (-4423));
      explosion0.setMapPosition((-4423), (-4423));
      // Undeclared exception!
      try { 
        explosion0.draw((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Entity.Explosion", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Explosion explosion0 = new Explosion((-4423), (-4423));
      explosion0.update();
      assertFalse(explosion0.shouldRemove());
  }

  @Test
  public void test2()  throws Throwable  {
      Explosion explosion0 = new Explosion((-4423), (-4423));
      boolean boolean0 = explosion0.shouldRemove();
      assertFalse(boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      Explosion explosion0 = new Explosion(1189, 574);
      explosion0.setMapPosition(1189, 574);
      assertFalse(explosion0.shouldRemove());
  }
}
