/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Dec 07 00:03:15 EET 2016
 */

package Entity;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class Player_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(4000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "Entity.Player"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Player_ESTest_scaffolding.class.getClassLoader() ,
      "javazoom.jl.decoder.Obuffer",
      "org.tritonus.share.StringHashedSet",
      "Entity.Animation",
      "javazoom.jl.decoder.DecoderErrors",
      "javazoom.jl.decoder.BitstreamErrors",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFileFormat",
      "org.tritonus.share.TDebug",
      "org.tritonus.share.sampled.AudioFormats",
      "Entity.Player",
      "org.tritonus.share.TCircularBuffer",
      "org.tritonus.share.sampled.file.TAudioFileReader",
      "javazoom.jl.decoder.Equalizer",
      "Audio.AudioPlayer",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFormat",
      "javazoom.spi.mpeg.sampled.file.MpegFileFormatType",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFileReader",
      "javazoom.spi.mpeg.sampled.file.MpegEncoding",
      "org.tritonus.share.TDebug$AssertException",
      "org.tritonus.share.sampled.convert.TFormatConversionProvider",
      "javazoom.jl.decoder.Bitstream",
      "org.tritonus.share.sampled.TAudioFormat",
      "org.tritonus.share.TCircularBuffer$Trigger",
      "org.tritonus.share.sampled.convert.TAudioInputStream",
      "javazoom.jl.decoder.DecoderException",
      "javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream$DMAISObuffer",
      "javazoom.jl.decoder.Decoder",
      "javazoom.spi.mpeg.sampled.file.tag.TagParseListener",
      "javazoom.jl.decoder.Header",
      "javazoom.spi.mpeg.sampled.file.IcyListener",
      "javazoom.jl.decoder.LayerIDecoder",
      "javazoom.jl.decoder.JavaLayerException",
      "javazoom.spi.mpeg.sampled.convert.MpegFormatConversionProvider",
      "javazoom.spi.mpeg.sampled.file.tag.IcyInputStream",
      "javazoom.jl.decoder.FrameDecoder",
      "javazoom.jl.decoder.OutputChannels",
      "org.tritonus.share.sampled.convert.TSimpleFormatConversionProvider",
      "javazoom.jl.decoder.Crc16",
      "javazoom.jl.decoder.JavaLayerErrors",
      "javazoom.spi.PropertiesContainer",
      "javazoom.jl.decoder.Decoder$Params",
      "Entity.MapObject",
      "org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream",
      "org.tritonus.share.sampled.file.TAudioFileFormat",
      "TileMap.TileMap",
      "javazoom.spi.mpeg.sampled.file.tag.MP3MetadataParser",
      "org.tritonus.share.ArraySet",
      "Entity.Enemy",
      "javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream",
      "javazoom.jl.decoder.LayerIIDecoder",
      "org.tritonus.share.sampled.convert.TEncodingFormatConversionProvider",
      "javazoom.jl.decoder.BitstreamException",
      "org.tritonus.share.sampled.Encodings",
      "javazoom.jl.decoder.SampleBuffer",
      "javazoom.jl.decoder.LayerIIIDecoder"
    );
  } 
}
