/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 06 22:27:57 EET 2016
 */

package Audio;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class AudioPlayer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(4000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "Audio.AudioPlayer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AudioPlayer_ESTest_scaffolding.class.getClassLoader() ,
      "javazoom.spi.mpeg.sampled.file.tag.MP3MetadataParser",
      "javazoom.spi.mpeg.sampled.file.tag.IcyInputStream",
      "javazoom.spi.mpeg.sampled.file.MpegEncoding",
      "org.tritonus.share.TDebug$AssertException",
      "javazoom.jl.decoder.BitstreamErrors",
      "javazoom.jl.decoder.Bitstream",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFileFormat",
      "org.tritonus.share.TDebug",
      "org.tritonus.share.sampled.TAudioFormat",
      "javazoom.jl.decoder.Crc16",
      "javazoom.jl.decoder.JavaLayerErrors",
      "org.tritonus.share.sampled.file.TAudioFileReader",
      "javazoom.spi.mpeg.sampled.file.tag.TagParseListener",
      "org.tritonus.share.sampled.file.TAudioFileFormat",
      "javazoom.jl.decoder.Header",
      "javazoom.jl.decoder.BitstreamException",
      "Audio.AudioPlayer",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFormat",
      "javazoom.spi.mpeg.sampled.file.MpegAudioFileReader",
      "javazoom.jl.decoder.JavaLayerException"
    );
  } 
}
