/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 22:27:57 EET 2016
 */

package Audio;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class AudioPlayer_ESTest extends AudioPlayer_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      AudioPlayer audioPlayer0 = new AudioPlayer("A@%m8);JGUfTt");
      audioPlayer0.play();
  }

  @Test
  public void test1()  throws Throwable  {
      AudioPlayer audioPlayer0 = new AudioPlayer("A@%m8);JGUfTt");
      // Undeclared exception!
      try { 
        audioPlayer0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Audio.AudioPlayer", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      AudioPlayer audioPlayer0 = new AudioPlayer("");
      // Undeclared exception!
      try { 
        audioPlayer0.stop();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Audio.AudioPlayer", e);
      }
  }
}
