/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 22:49:42 EET 2016
 */

package GameState;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class GameStateManager_ESTest extends GameStateManager_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.keyReleased(1007);
  }

  @Test
  public void test1()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.setState(1);
      gameStateManager0.draw((Graphics2D) null);
  }

  @Test
  public void test2()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.setState(1325);
      // Undeclared exception!
      try { 
        gameStateManager0.setState(1325);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1325
         //
         assertThrownBy("GameState.GameStateManager", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.setState((-3488));
      // Undeclared exception!
      try { 
        gameStateManager0.keyReleased((-3488));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -3488
         //
         assertThrownBy("GameState.GameStateManager", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.setState(1909);
      // Undeclared exception!
      try { 
        gameStateManager0.keyPressed(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1909
         //
         assertThrownBy("GameState.GameStateManager", e);
      }
  }

  @Test
  public void test5()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.draw((Graphics2D) null);
  }

  @Test
  public void test6()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.keyPressed(1909);
  }

  @Test
  public void test7()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.setState(1);
      gameStateManager0.update();
  }

  @Test
  public void test8()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      gameStateManager0.update();
  }
}
