/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 22:53:11 EET 2016
 */

package GameState;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Level1State_ESTest extends Level1State_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(2999);
  }

  @Test
  public void test01()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(0);
  }

  @Test
  public void test02()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed(859);
  }

  @Test
  public void test03()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed((-3312));
  }

  @Test
  public void test04()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      // Undeclared exception!
      try { 
        level1State0.draw((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.Background", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.init();
  }

  @Test
  public void test06()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(87);
  }

  @Test
  public void test07()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(38);
  }

  @Test
  public void test08()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(39);
  }

  @Test
  public void test09()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(37);
  }

  @Test
  public void test10()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyReleased(40);
  }

  @Test
  public void test11()  throws Throwable  {
      Level1State level1State0 = new Level1State((GameStateManager) null);
      level1State0.keyPressed(70);
  }

  @Test
  public void test12()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed(82);
  }

  @Test
  public void test13()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed(69);
  }

  @Test
  public void test14()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed(37);
  }

  @Test
  public void test15()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.keyPressed(40);
  }

  @Test
  public void test16()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      Level1State level1State0 = new Level1State(gameStateManager0);
      level1State0.update();
  }
}
