/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 06 22:55:18 EET 2016
 */

package GameState;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.Graphics2D;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class MenuState_ESTest extends MenuState_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyPressed(498);
  }

  @Test
  public void test01()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyPressed(0);
  }

  @Test
  public void test02()  throws Throwable  {
      MenuState menuState0 = new MenuState((GameStateManager) null);
      // Undeclared exception!
      try { 
        menuState0.keyPressed(10);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("GameState.MenuState", e);
      }
  }

  @Test
  public void test03()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      gameStateManager0.setState(498);
      // Undeclared exception!
      try { 
        menuState0.keyPressed(10);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 498
         //
         assertThrownBy("GameState.GameStateManager", e);
      }
  }

  @Test
  public void test04()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      // Undeclared exception!
      try { 
        menuState0.draw((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("TileMap.Background", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyReleased(38);
  }

  @Test
  public void test06()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyPressed(38);
      menuState0.keyPressed(38);
  }

  @Test
  public void test07()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyPressed(40);
      menuState0.keyPressed(40);
      menuState0.keyPressed(40);
  }

  @Test
  public void test08()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.keyPressed(10);
  }

  @Test
  public void test09()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.init();
  }

  @Test
  public void test10()  throws Throwable  {
      GameStateManager gameStateManager0 = new GameStateManager();
      MenuState menuState0 = new MenuState(gameStateManager0);
      menuState0.update();
  }
}
